name: 'Get Commit SHA Info'
description: 'Prints out the commit info'
branding:
  icon: 'activity'
  color: 'purple'
inputs:
  name:
    description: 'Your name'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
